### ISSUE TITLE
NameError: uninitialized constant ActiveRecordQueryTrace with test

### ISSUE THREAD

**Issue by shingo-nakanishi** [ruckus/active-record-query-trace#25]
## Only use development
```rb
group :development do
  gem 'active_record_query_trace'
end
```

## rails s is work
```
% bin/rails s
```
work!

## RAILS_ENV=test bin/rails s is not work
```
RAILS_ENV=test bin/rails s
```

### Error message
uninitialized constant ActiveRecordQueryTrace (NameError)

## With RSpec is same error
```
% bundle exec rspec
```

### Error message
bundler: failed to load command: rspec 
NameError: uninitialized constant ActiveRecordQueryTrace

**Comment by ruckus** [comment]
You'll need to load the gem in `test` environment as well:

```
group :development, :test do
   gem 'active_record_query_trace'
end
```

Or just dont use an environment scope at all

**Comment by shingo-nakanishi** [comment]
@ruckus Hi, Thank you response. but I want to use it only development.

**Comment by ruckus** [comment]
To run your tests you will need to load the gem in test environment

**Comment by wynksaiddestroy** [comment]
@shingo-nakanishi: Just change the initializer in `config/initializers/active_record_query_trace.rb` as follow:

```ruby
ActiveRecordQueryTrace.enabled = true if defined?(ActiveRecordQueryTrace)
```
